# Generated by Django 5.2.1 on 2025-08-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_photo', models.ImageField(upload_to='developer/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github', models.URLField()),
                ('gist', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='projects/')),
                ('developers', models.ManyToManyField(to='projects.devloper')),
            ],
        ),
    ]
