# Generated by Django 5.2.1 on 2025-09-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gist',
            field=models.URLField(),
        ),
    ]
