# Generated by Django 5.2.1 on 2025-05-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
