# Generated by Django 5.2.1 on 2025-07-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_author_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Author", "verbose_name_plural": "Authors"},
        ),
        migrations.AddField(
            model_name="blog",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
